"use client";

import type { Post } from "@/lib/api/types";

const labels: Record<string, string> = { draft: "مسودة", in_review: "قيد المراجعة", changes_requested: "مطلوب تعديل", approved: "معتمد", scheduled: "مجدول", published: "منشور", archived: "مؤرشف" };

export function PostPublishingPanel({ post, scheduleValue, onScheduleValue, busy, onAction }: { post: Post | null; scheduleValue: string; onScheduleValue: (value: string) => void; busy: boolean; onAction: (action: string) => void }) {
  const status = post?.status ?? "draft";
  const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  return <section className="premium-card space-y-3 p-4"><div className="flex items-center justify-between"><h2 className="font-bold">النشر</h2><span className="rounded-full bg-muted px-2 py-1 text-xs font-bold">{labels[status] ?? status}</span></div>{post ? <>{["draft", "changes_requested"].includes(status) ? <button type="button" disabled={busy} onClick={() => onAction("submit-review")} className="w-full rounded-lg border border-border p-2 text-sm font-bold">إرسال للمراجعة</button> : null}{status === "in_review" ? <button type="button" disabled={busy} onClick={() => onAction("approve")} className="w-full rounded-lg border border-border p-2 text-sm font-bold">اعتماد</button> : null}{["draft", "in_review", "approved"].includes(status) ? <button type="button" disabled={busy} onClick={() => onAction("publish")} className="w-full rounded-lg bg-primary p-2 text-sm font-bold text-primary-foreground">نشر الآن</button> : null}{status === "published" ? <button type="button" disabled={busy} onClick={() => onAction("unpublish")} className="w-full rounded-lg border border-border p-2 text-sm font-bold">إلغاء النشر</button> : null}{status === "scheduled" ? <button type="button" disabled={busy} onClick={() => onAction("cancel-schedule")} className="w-full rounded-lg border border-border p-2 text-sm font-bold">إلغاء الجدولة</button> : <><input type="datetime-local" value={scheduleValue} min={new Date().toISOString().slice(0, 16)} onChange={(event) => onScheduleValue(event.target.value)} className="w-full rounded-lg border border-border bg-background p-2 text-sm" /><p className="text-[11px] text-muted-foreground">سيتم النشر بتوقيت {timezone}</p><button type="button" disabled={busy || !scheduleValue} onClick={() => onAction("schedule")} className="w-full rounded-lg border border-border p-2 text-sm font-bold">جدولة</button></>}</> : <p className="text-xs text-muted-foreground">احفظ المسودة أولاً لتفعيل إجراءات سير النشر.</p>}</section>;
}
